# Delete these routes and define your own shop routes here

webgriffe_sylius_italian_invoiceable_order_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: WebgriffeSyliusItalianInvoiceableOrderPlugin:Greeting:staticallyGreet
        name: ~

webgriffe_sylius_italian_invoiceable_order_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: WebgriffeSyliusItalianInvoiceableOrderPlugin:Greeting:dynamicallyGreet
        name: ~
